### PR TITLE
Branching Workflows

### LINKED ISSUE #6: Research Various Branching Workflows
Research the various branching workflows and different ways of using them.

### PR DESCRIPTION
**Pull request by RivkaBerlinski**
Explanation of main Git workflows
Closes #6

### CODE REVIEW

**Comment by RivkaBerlinski** [comment]
We have uploaded an initial file open to changes.
regarding the alternatives.
We found that there are additional workflows that we were not asked to detail.
Should we also study them in order to present them as alternatives to the workflows we detailed in the MD file?

**Comment by bdsoha** [comment]
> We have uploaded an initial file open to changes. regarding the alternatives. We found that there are additional workflows that we were not asked to detail. Should we also study them in order to present them as alternatives to the workflows we detailed in the MD file?

Which workflows?

**Comment by bdsoha** [comment]
Please add a mention to your issue in the description *(i.e. `Closes #6`)*.

**Comment by RivkaBerlinski** [comment]
Gitflow Workflow

**Comment by RivkaBerlinski** [comment]
Sorry,
We see that the couples got mixed up in the Review requested,
I work with Chana Naimen And you put me in Review requested With Miriam R.

Is this a mistake?

**Comment by bdsoha** [comment]
> Sorry, We see that the couples got mixed up in the Review requested, I work with Chana Naimen And you put me in Review requested With Miriam R.
> 
> Is this a mistake?

You are welcome to fix it.

**Comment by RivkaBerlinski** [comment]
We found a successful tool that simulates markdownlint
When selecting an MD file it gives the comments required for the change,
can we use them or we need instal ``markdownlint``?

**Comment by RivkaZishinski** [comment]
we think that we end the code review - can we merge the PR?

**Pull request merged**
